<a href="https://colab.research.google.com/github/yunjeong-chang/2021_Artificial-Intelligence/blob/main/4%EC%A3%BC%EC%B0%A8/exercise/4%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B52_%EB%8B%A4%EC%A4%91%EC%84%A0%ED%98%95%EB%B6%84%EB%A5%98(%EC%86%8C%ED%94%84%ED%8A%B8%EB%A7%A5%EC%8A%A4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Softmax classification
- 클래스가 3개 이상인 경우

## 데이터 로더

In [9]:
import torch
import torch.optim as optim

# For reproducibility
torch.manual_seed(1)

x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0] #클래스가 3개 (0, 1, 2)

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

print(x_train[:5]) # 앞의 다섯 개
print(y_train[:5])

tensor([[1., 2., 1., 1.],
        [2., 1., 3., 2.],
        [3., 1., 3., 4.],
        [4., 1., 5., 5.],
        [1., 7., 5., 5.]])
tensor([2, 2, 2, 1, 1])


In [10]:
print(y_train)
print(y_train.unsqueeze(1))

nb_class = 3 #클래스가 3개 (0, 1, 2)
nb_data = len(y_train)

y_one_hot = torch.zeros(nb_data, nb_class)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)

print(y_one_hot)

tensor([2, 2, 2, 1, 1, 1, 0, 0])
tensor([[2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [0],
        [0]])
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


## 모델 학습

In [11]:
import torch.nn.functional as F  # for softmax

# 모델 초기화
# feature 4개, 3개의 클래스
nb_class = 3
nb_data = len(y_train)

W = torch.zeros((4, nb_class), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산 (1)
    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1) # or .mm or @
    
    # cost 표현번 1번 예시
    y_one_hot = torch.zeros(nb_data, nb_class)
    y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
    cost = (y_one_hot * -torch.log(F.softmax(hypothesis, dim=1))).sum(dim=1).mean()
    
    # cost 표현법 2번 예시
    # cross_entropy를 사용하면 scatter 함수를 이용한 one_hot_encoding을 안해도 됨
    # cost = F.cross_entropy((x_train.matmul(W) + b), y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 1.036919
Epoch  200/1000 Cost: 1.010905
Epoch  300/1000 Cost: 0.991541
Epoch  400/1000 Cost: 0.974942
Epoch  500/1000 Cost: 0.959928
Epoch  600/1000 Cost: 0.946149
Epoch  700/1000 Cost: 0.933492
Epoch  800/1000 Cost: 0.921898
Epoch  900/1000 Cost: 0.911302
Epoch 1000/1000 Cost: 0.901625


## 데이터 평가

In [13]:
# 학습된 W,b를 통한 클래스 예측
hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
predict = torch.argmax(hypothesis, dim=1) # argmax : 가장 큰 값의 인덱스를 return

print(hypothesis)
print(predict)
print(y_train)

# 정확도 계산 
correct_prediction = predict.float() == y_train
print(correct_prediction)
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[0.3633, 0.1321, 0.5046],
        [0.1075, 0.3747, 0.5178],
        [0.0338, 0.4811, 0.4851],
        [0.0120, 0.5703, 0.4177],
        [0.9002, 0.0161, 0.0838],
        [0.1476, 0.7789, 0.0735],
        [0.8375, 0.0747, 0.0878],
        [0.8986, 0.0490, 0.0524]], grad_fn=<SoftmaxBackward>)
tensor([2, 2, 2, 1, 0, 1, 0, 0])
tensor([2, 2, 2, 1, 1, 1, 0, 0])
tensor([ True,  True,  True,  True, False,  True,  True,  True])
The model has an accuracy of 87.50% for the training set.
